### ISSUE TITLE
chokidar support - fsevents

### ISSUE THREAD

**Issue by MadLittleMods** [Jam3/devtool#51]
Using `chokidar` inside an gulpfile.js but not in any code called by `web.js`: `devtool web.js` throws this error, while `node web.js` doesn't.

 - `chokidar@1.4.3`
 - `devtool@1.7.0`
 - `node@4.2.3`

https://github.com/paulmillr/chokidar/blob/69a549315cd862f54942c042edfd42edfabadb55/lib/fsevents-handler.js#L22

```
TypeError: fsevents is not a function
    at createFSEventsInstance (/some-project/node_modules/chokidar/lib/fsevents-handler.js:22:11)
    at setFSEventsListener (/some-project/node_modules/chokidar/lib/fsevents-handler.js:67:16)
    at FSWatcher.FsEventsHandler._watchWithFsEvents (/some-project/node_modules/chokidar/lib/fsevents-handler.js:211:16)
    at FSWatcher.<anonymous> (/some-project/node_modules/chokidar/lib/fsevents-handler.js:342:25)
    at LOOP (fs.js:1623:14)
    at doNTCallback0 (node.js:443:9)
    at process._tickDomainCallback (node.js:413:13)
```

**Comment by MadLittleMods** [comment]
It looks like this has fixed somewhere between `devtool@1.7.0` and  `devtool@1.7.4`. Seems to work fine with `devtool@1.7.4`.
