### ISSUE TITLE
ioredis support

### ISSUE THREAD

**Issue by MadLittleMods** [Jam3/devtool#49]
Using `ioredis` inside an app: `devtool web.js` throws this error, while `node web.js` doesn't.

 - `ioredis@1.15.1`
 - `devtool@1.7.4`
 - `node@4.2.3`

https://github.com/luin/ioredis/blob/48d9701ba9e245a8a650c96f59762d1344e417ef/lib/redis/parser.js#L18
```
TypeError: this.Parser is not a function
    at Redis.exports.initParser (/some-project/node_modules/ioredis/lib/redis/parser.js:18:22)
    at Socket.<anonymous> (/some-project/node_modules/ioredis/lib/redis/event_handler.js:30:10)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
```

**Comment by mattdesl** [comment]
Hmm I wonder how that code is even supposed to run? I don't see `this.Parser` defined anywhwere.

**Comment by MadLittleMods** [comment]
@mattdesl I also had a lot of trouble looking into how this work before posting. You really have to go down the rabbit hole to find it.

`./lib/redis/parser.js iniParser -> this.Parser()` <- `./lib/redis/event_handler.js l30` <- `./lib/redis.js l273` .....  `./lib/redis.js l108`

**Comment by mattdesl** [comment]
Just tested with node@5, ioredis@1.15.1, devtool@1.8.3, redis-server@3.0.5 and not getting any errors.

I tested with the following file:
https://github.com/luin/ioredis/blob/012ad51d0c4a803f08949e1a1e85f6084ed98369/examples/basic_operations.js

**Comment by MadLittleMods** [comment]
@mattdesl Tried node 5 but currently blocked by https://github.com/Jam3/devtool/issues/54 - Also would be nice to stick LTS version, https://github.com/Jam3/devtool/issues/34

**Comment by MadLittleMods** [comment]
Confirmed working with `node@5.9.0` and `devtool@1.8.3` or `devtool@1.9.1`.

Really weird that execution works in the later `devtool` which uses node 5 via electron.

The code works just fine standalone on `node@0.10.x` and `node@4.x/x`
